package de.leonardo.theme.gothic

import androidx.compose.material3.ColorScheme
import androidx.compose.runtime.Composable
import androidx.compose.ui.graphics.Color

internal val GothicLightColorScheme: ColorScheme
    @Composable get() = ColorScheme(
        primary = primaryLight,
        onPrimary = onPrimaryLight,
        primaryContainer = primaryContainerLight,
        onPrimaryContainer = onPrimaryContainerLight,
        secondary = secondaryLight,
        onSecondary = onSecondaryLight,
        secondaryContainer = secondaryContainerLight,
        onSecondaryContainer = onSecondaryContainerLight,
        tertiary = tertiaryLight,
        onTertiary = onTertiaryLight,
        tertiaryContainer = tertiaryContainerLight,
        onTertiaryContainer = onTertiaryContainerLight,
        error = errorLight,
        onError = onErrorLight,
        errorContainer = errorContainerLight,
        onErrorContainer = onErrorContainerLight,
        background = backgroundLight,
        onBackground = onBackgroundLight,
        surface = surfaceLight,
        onSurface = onSurfaceLight,
        surfaceVariant = surfaceVariantLight,
        onSurfaceVariant = onSurfaceVariantLight,
        outline = outlineLight,
        outlineVariant = outlineVariantLight,
        scrim = scrimLight,
        inverseSurface = inverseSurfaceLight,
        inverseOnSurface = inverseOnSurfaceLight,
        inversePrimary = inversePrimaryLight,
        surfaceDim = surfaceDimLight,
        surfaceBright = surfaceBrightLight,
        surfaceContainerLowest = surfaceContainerLowestLight,
        surfaceContainerLow = surfaceContainerLowLight,
        surfaceContainer = surfaceContainerLight,
        surfaceContainerHigh = surfaceContainerHighLight,
        surfaceContainerHighest = surfaceContainerHighestLight,
        surfaceTint = primaryLight,
    )

val GothicDarkColorScheme: ColorScheme
    @Composable get() = ColorScheme(
        primary = primaryDark,
        onPrimary = onPrimaryDark,
        primaryContainer = primaryContainerDark,
        onPrimaryContainer = onPrimaryContainerDark,
        secondary = secondaryDark,
        onSecondary = onSecondaryDark,
        secondaryContainer = secondaryContainerDark,
        onSecondaryContainer = onSecondaryContainerDark,
        tertiary = tertiaryDark,
        onTertiary = onTertiaryDark,
        tertiaryContainer = tertiaryContainerDark,
        onTertiaryContainer = onTertiaryContainerDark,
        error = errorDark,
        onError = onErrorDark,
        errorContainer = errorContainerDark,
        onErrorContainer = onErrorContainerDark,
        background = backgroundDark,
        onBackground = onBackgroundDark,
        surface = surfaceDark,
        onSurface = onSurfaceDark,
        surfaceVariant = surfaceVariantDark,
        onSurfaceVariant = onSurfaceVariantDark,
        outline = outlineDark,
        outlineVariant = outlineVariantDark,
        scrim = scrimDark,
        inverseSurface = inverseSurfaceDark,
        inverseOnSurface = inverseOnSurfaceDark,
        inversePrimary = inversePrimaryDark,
        surfaceDim = surfaceDimDark,
        surfaceBright = surfaceBrightDark,
        surfaceContainerLowest = surfaceContainerLowestDark,
        surfaceContainerLow = surfaceContainerLowDark,
        surfaceContainer = surfaceContainerDark,
        surfaceContainerHigh = surfaceContainerHighDark,
        surfaceContainerHighest = surfaceContainerHighestDark,
        surfaceTint = primaryDark
    )

val primaryLight = Color(0xFF0F6B57)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFA2F2D9)
val onPrimaryContainerLight = Color(0xFF005141)
val secondaryLight = Color(0xFF4B635B)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFCDE9DE)
val onSecondaryContainerLight = Color(0xFF344C44)
val tertiaryLight = Color(0xFF416277)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFC5E7FF)
val onTertiaryContainerLight = Color(0xFF284B5E)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFF5FBF6)
val onBackgroundLight = Color(0xFF171D1B)
val surfaceLight = Color(0xFFF5FBF6)
val onSurfaceLight = Color(0xFF171D1B)
val surfaceVariantLight = Color(0xFFDBE5DF)
val onSurfaceVariantLight = Color(0xFF3F4945)
val outlineLight = Color(0xFF6F7975)
val outlineVariantLight = Color(0xFFBFC9C4)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2B322F)
val inverseOnSurfaceLight = Color(0xFFECF2EE)
val inversePrimaryLight = Color(0xFF86D6BE)
val surfaceDimLight = Color(0xFFD5DBD7)
val surfaceBrightLight = Color(0xFFF5FBF6)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFEFF5F1)
val surfaceContainerLight = Color(0xFFE9EFEB)
val surfaceContainerHighLight = Color(0xFFE3EAE5)
val surfaceContainerHighestLight = Color(0xFFDEE4E0)

val primaryDark = Color(0xFF86D6BE)
val onPrimaryDark = Color(0xFF00382C)
val primaryContainerDark = Color(0xFF005141)
val onPrimaryContainerDark = Color(0xFFA2F2D9)
val secondaryDark = Color(0xFFB2CCC2)
val onSecondaryDark = Color(0xFF1D352E)
val secondaryContainerDark = Color(0xFF344C44)
val onSecondaryContainerDark = Color(0xFFCDE9DE)
val tertiaryDark = Color(0xFFA9CBE2)
val onTertiaryDark = Color(0xFF0E3446)
val tertiaryContainerDark = Color(0xFF284B5E)
val onTertiaryContainerDark = Color(0xFFC5E7FF)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF0F1512)
val onBackgroundDark = Color(0xFFDEE4E0)
val surfaceDark = Color(0xFF0F1512)
val onSurfaceDark = Color(0xFFDEE4E0)
val surfaceVariantDark = Color(0xFF3F4945)
val onSurfaceVariantDark = Color(0xFFBFC9C4)
val outlineDark = Color(0xFF89938E)
val outlineVariantDark = Color(0xFF3F4945)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFDEE4E0)
val inverseOnSurfaceDark = Color(0xFF2B322F)
val inversePrimaryDark = Color(0xFF0F6B57)
val surfaceDimDark = Color(0xFF0F1512)
val surfaceBrightDark = Color(0xFF343B38)
val surfaceContainerLowestDark = Color(0xFF090F0D)
val surfaceContainerLowDark = Color(0xFF171D1B)
val surfaceContainerDark = Color(0xFF1B211F)
val surfaceContainerHighDark = Color(0xFF252B29)
val surfaceContainerHighestDark = Color(0xFF303633)